import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "node:module";
import { copyFile } from "node:fs/promises";
import path from "node:path";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

// Where the built plugin is written. Defaults to the local test vault so the
// plugin can be loaded in Obsidian without a separate copy step. Override with
// GENE_CODE_VAULT_PLUGIN_DIR to target a different vault.
const outDir = process.env.GENE_CODE_VAULT_PLUGIN_DIR ?? import.meta.dirname;

// `@gene-code/core` is intentionally NOT external — it is a pure string-based
// SVG renderer with no Node/DOM deps, so we bundle it straight into main.js.
const context = await esbuild.context({
  banner: { js: banner },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: ["obsidian", "electron", ...builtinModules],
  format: "cjs",
  target: "es2021",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: path.join(outDir, "main.js"),
  minify: prod,
});

async function copyAssets() {
  await Promise.all([
    copyFile("manifest.json", path.join(outDir, "manifest.json")),
    copyFile("styles.css", path.join(outDir, "styles.css")),
  ]);
}

if (prod) {
  await context.rebuild();
  await copyAssets();
  await context.dispose();
  console.log(`gene-code plugin built to ${outDir}`);
  process.exit(0);
} else {
  await copyAssets();
  await context.watch();
  console.log(`gene-code plugin watching; output -> ${outDir}`);
}
